---

# Convert variable key/val vpc_filter array into dict object
# Returns:
# * _fact_key_val_dict
- include_tasks: _expand_key_val_dict.yml
  vars:
    key_val_dict: "{{ igw.vpc_filter | default() }}"

- name: gather vpc facts
  ec2_vpc_net_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_igw_profile | default(omit) }}"
    region: "{{ igw.region | default(aws_vpc_igw_default_region) }}"
    filters: "{{ _fact_key_val_dict }}"
  register: _vpc_igw_vpc

- name: fail if vpc was not found
  assert:
    that:
      - _vpc_igw_vpc.vpcs is defined
      - _vpc_igw_vpc.vpcs | length == 1
    msg: Not exactly one VPC has been found

- name: set vpc id
  set_fact:
    aws_vpc_igw_vpc_id: "{{ _vpc_igw_vpc.vpcs[0].id }}"

- name: set vpc cidr
  set_fact:
    aws_vpc_igw_vpc_cidr: "{{ _vpc_igw_vpc.vpcs[0].cidr_block }}"
